name = "milou"
description = ""
version = "0.1.0-dev"

authors = ["Tristan DHERSIN"]
maintainers = ["Tristan DHERSIN <tristan.dhersin@gmail.com>"]
maintainers-logins = ["TristanBrouille"]
licenses = "MIT OR Apache-2.0 WITH LLVM-exception"
website = ""
tags = []

#[[depends-on]]
#nucleo_g431kb = "*"
#[[pins]]
#nucleo_g431kb = {path = ".."}


[[depends-on]]
light_tasking_stm32g431 = "*"
gnat_arm_elf = "*"